apiVersion: v1
kind: Service
metadata:
  name: kubedemo-service
spec:
  selector:
    app: kubedemo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30089
  type: NodePort
